# Generated by Django 5.2.1 on 2025-05-28 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbetes', '0002_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('orth', models.CharField(blank=True, max_length=100)),
                ('gram', models.CharField(blank=True, max_length=100)),
                ('frase', models.TextField()),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('data', models.CharField(blank=True, max_length=50)),
                ('definicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='verbetes.definition')),
                ('verbete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='verbetes.verbete')),
            ],
        ),
    ]
