# Generated by Django 5.2.1 on 2025-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verbete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('classe_gramatical', models.CharField(blank=True, max_length=50)),
                ('etimologia', models.TextField(blank=True)),
                ('primeira_ocorrencia', models.TextField(blank=True)),
                ('data_ocorrencia', models.CharField(blank=True, max_length=100)),
                ('autores', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateField(blank=True, null=True)),
                ('atualizado_em', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
