# Generated by Django 5.2.1 on 2025-05-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensenumber', models.IntegerField()),
                ('definition', models.TextField()),
                ('verbete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definicoes', to='verbetes.verbete')),
            ],
        ),
    ]
