# Generated by Django 5.2.1 on 2025-06-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbetes', '0003_ocorrenciacorpus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciacorpus',
            name='titulo_obra',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
