# Generated by Django 5.2.1 on 2025-06-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbetes', '0004_ocorrenciacorpus_titulo_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciacorpus',
            name='slug_obra',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='ocorrenciacorpus',
            name='titulo_obra',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
