# Generated by Django 5.2.1 on 2025-06-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbetes', '0005_ocorrenciacorpus_slug_obra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciacorpus',
            name='pagina_obra',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
