# Generated by Django 5.2.1 on 2025-05-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('caminho_arquivo', models.CharField(max_length=300)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
