# Generated by Django 5.2.1 on 2025-06-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_digital', '0002_alter_obra_options_obra_conteudo_html_processado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='data_referencia',
            field=models.CharField(blank=True, help_text='Data/ano de referência da obra (ex: 1750, c. 1800, Século XVIII).', max_length=100, null=True),
        ),
    ]
